TRUNCATE TABLE MessageMaster;
BEGIN TRANSACTION;
INSERT INTO MessageMaster VALUES ( 'E0001','検索条件に該当するデータが存在しません。','Does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0002','{0}を入力してください。','{0} is required.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0003','対象が選択されていません。','The subject has not been selected.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0005','ユーザＩＤまたはパスワードが不正です。','User ID or password is invalid.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0006','システムを利用する権限がありません。 ({0})','You do not have permission to use the system. ({0})','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0007','ログインIDに事務室が割り当てられていません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0009','「{0}」は、機種依存文字のため入力できません。※“タブ”や一部の文字は「」の中が空欄で表示されます。','The [{0}] is a platform dependent character and cannot be entered. *"Tabs" and some characters are displayed with a blank space in the brackets.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0012','{0}に{1}以外が入力されています。','Something other than {1}has been entered in {0}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0016','既に存在しています。','It already exists.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0017','指定された{0}は存在しません。','Specified {0} does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0019','サーバーからの印刷処理に失敗しました。{0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0025','{0}は日付または時刻として正しくありません。','{0} is incorrect as a date or time.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0028','{0}は{1}より未来の日付を指定することはできません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0029','{0}は{1}より過去の日付を指定することはできません。','{0} does not allow you to specify a date before {1}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0034','{0}は小さい方から順に入力してください。','For {0}, please enter in order from smallest.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0035','{0}は{1}から{2}の範囲で入力してください。','For {0} please enter a range of {1} to {2}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0040','{0}に同じ内容は入力できません。','Same content cannot be entered into {0}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0041','{0}と{1}に同じ内容は入力できません。','Same content cannot be entered into {0} and {1}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0042','対象のデータが存在しません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0044','エラーの内容を確認してください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0045','本処理は、他のユーザで実行中です。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0047','{0}が選択されていない場合は、{1}は入力できません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0052','対象ファイルが存在しません。','The target file does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0057','{0}は、{1}桁で入力してください。','{0}, please enter {1} digits.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0058','{0}は、{1}桁以内で入力してください。','{0}, please enter {1} digits or less.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0059','{0}は、{1}桁以上で入力してください。','{0}, please enter {1} digits or more.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0060','該当データは、他のユーザで削除されました。','Deleted by another user.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0061','他のユーザで内容が更新されました。現在の内容を破棄の上、再オペレーションしてください。','Content has been updated by another user. Please discard the current content and try again.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0062','処理に時間がかかり過ぎるため、処理を中断しました。条件を変更して再度実行してください。','Process has timed out. Please change the conditions and try again.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0069','利用可能期間を超過しました。','Available runtime has been exceeded.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0075','Excelファイルの「{0}」シートにデータがありません。','Excel file "{0}" There is no data in the sheet.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0076','Excelファイルに「{0}」シートが存在しません。','The Excel file "{0}" sheet does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0077','Excelファイルの「{0}」シートにヘッダ行がありません。','Excel file "{0}" does not have a header line on the sheet.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0078','Excelファイルのヘッダ行が違います。行={0} 列={1} 正しい値={2} 実際の値={3}','Header line in the Excel file is different. Line={0} column={1} correct value={2} actual value={3}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0079','Excelファイルにデータがありません。','There is no data in the Excel file.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0080','{0}を入力してください。行={1}','{0} is required. Line={1}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0081','{0}は、{1}桁で入力してください。行={2}','{0}, please enter in the {1} digits. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0082','{0}は、{1}桁以内で入力してください。行={2}','{0}, please enter within {1} digits. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0083','{0}は、{1}桁以上で入力してください。行={2}','{0}, please enter as {1} or more digits. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0084','{0}に{1}以外が入力されています。行={2}','{0} than {1} it has been entered into. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0085','{0}が{1}に登録されていません。行={2}','{0} is not registered to {1}. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0086','ファイルの上限サイズを超えています。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0087','ファイルが不正です。{0}','File is invalid. {0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0088','画像ファイルではありません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0090','{0}処理を実行できませんでした。システム管理者に問い合わせてください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0091','{0}処理でエラーが発生しました。エラー内容を確認してください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0092','キー項目が同じデータが存在します。行={0} キー項目={1}','Data with the same key item exists. Line={0} key={1}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0093','{0}は小さい方から順に入力してください。行={1}','Please enter in order from {0} small to large. Line={1}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0094','{0}は{1}から{2}の範囲で入力してください。行={3}','{0} Please enter in the range of {2} from {1}. Line={3}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0095','指定された{1}は存在しません。行={0}','Specified {1} does not exist. Line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0096','指定された{1}は既に存在しています。行={0}','Specified {1} already exists. Line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0098','取込ファイルの項目数が{1}ではありません。行={0}','The number of items in the uploaded file is not {1}. Line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0099','{1}行目と同じです。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0100','存在しない{1}です。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0101','{0}のアップロードでエラーが発生しました。','An error has occurred in the upload of {0}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0102','{0}は日付または時刻として正しくありません。行={1}','{0} is incorrect as a date or time. Line={1}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0103','他のユーザが既に実行しています。','Another user has already executed it.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1001','指定された{0}は既に存在しています。','The specified {0} already exists.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1002','検索条件が不足しています。検索条件の指定を追加してください。','Search criteria are missing. Please add additional search criteria specification.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1003','一切の項目の変更は不可です。行={0}','No changes to any item are allowed. Row = {0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1004','修正不可項目への修正があります。行={0}','There are corrections to non-modifiable items. Row = {0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1005','差戻理由と差戻者以外は変更できません。行={0}','Only the reason for the return and the sender of the return can be changed. Row = {0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1006','指定された{1}は科目の担当教員ではありません。行={0}','The specified {1} is not the lecturer in charge of the subject. Row = {0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1007','入力された勤務時間は既に登録されています。','The work hours entered are already registered.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1008','雇用期間外のため、登録できません。','Cannot register as outside employment period.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1009','深夜時間の登録はできません。','Late-night hours cannot be registered.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1010','勤務時間が6時間を超える場合、1時間以上の控除時間が必要です。','If the workday exceeds 6 hours, a deduction of at least 1 hour is required.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1011','勤務時間が週28時間を超えるため、登録できません。','Cannot register as the work hours exceed 28 hours per week.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1012','入力された個別単価は最低給与単価を下回っています。																													','The individual unit price entered is below the minimum salary unit price.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1013','承認対象の勤務データはありません。','There is no work data to be approved.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1014','Excelファイルに更新対象のデータ行がありません。','There are no rows of data in the Excel file to be updated.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1015','{1}が登録されている値と異なっています。行={0}','{1} is different from the registered value. Line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1016','他のユーザで内容が更新されました。現在の内容を破棄の上、ダウンロードから再オペレーションしてください。','The content has been updated by another user. Please discard the current contents and reoperate from the download.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1017','直近承認者が存在しないため、差戻できません。差戻す場合は学生を指定してください。行={0}','The most recent approver does not exist and cannot return the form. Please specify a student to send it back. line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1018','システム日付年度より過去の年度は登録できません。','You cannot register for years past the system date year.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1019','登録期間外のため、登録できません。','Registration is not available outside of the registration period.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1020','指定された個別単価は最低給与単価を下回っています。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1021','システム日付年度より過去の年度は登録できません。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1022','指定された予算区分は既に存在しています。予算区分を修正の上、アップロードから再オペレーションしてください。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1023','{0}は{1}以前の時刻を指定することはできません。','{0} cannot specify a time before {1}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1024','勤務時間が0以下になるような控除時間を指定することはできません。','You may not specify a deduction time that would result in less than zero hours worked.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1025','登録期間外のため、削除できません。','Cannot be deleted because it is outside the registration period.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1026','{0}には{1}を入力できません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1027','取込ファイルが存在しません。もう一度アップロードからやり直してください。','The file does not exist. Please try uploading the file again.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1028','同一の{0}が登録されています。行={1}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1029','入力された{0}は既に存在しています。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1030','ユーザの雇用部課以外のデータは登録できません。行 ={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1031','対象データに紐づく勤務情報が存在するため削除できません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1032','ユーザ区分が学生の場合、{0}できません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1033','給与支給日は勤務月の翌月を指定してください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1034','指定された授業に担当教員が指定されていません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0001','本機能は未実装です。','Under construction.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0005','{0}件を超えたため、これ以上表示できません。条件で絞り込んでください。','Search terms exceed the maximum of {0} results. Please refine conditions.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0006','{0}件を超えたため、これ以上表示できません。処理を実行し、件数を減らしてください。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0007','{0}件を超えたため、{0}件までの検索結果を表示します。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0008','{0}件を超えたため、表示できません。科目名を追記するか他の条件も指定してください。','Search terms exceed the maximum of {0} results. Please add course name or refine other conditions.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0009','今回の成績記入にて、再履修回数を超えました。問題がある場合は訂正して下さい。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1001','差戻を含む勤務を一括承認しようとしています。問題がなければ登録を押してください。','Trying to approve a batch of work including Returnings. If you are satisfied with the results, please press "Register".','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1002','同一日勤務情報が既に登録されています。','Work information for the same day is already registered.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1003','勤務時間が週20時間を超えています。週28時間は超えないようにしてください。','Work hours exceed 20 hours per week. Do not exceed 28 hours per week.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1004','1日の勤務時間が{0}時間を超えないようにしてください。','Do not exceed {0} hours per day.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1005','1週間の勤務時間が{0}時間を超えています。','Work hours per week exceed {0} hours.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1006','1ヶ月の勤務時間が{0}時間を超えています。','Work hours per month exceed {0} hours.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1007','勤務情報（開始時刻～校地移動）が登録されている値と異なっています。勤務情報は修正されません。行={0}','The work information (start time ～ school transfer) is　different from the registered value.The work information will not be modified.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1008','差戻された勤務データを承認します。行={0}','Approve the returned work data.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1009','雇用年度、社員番号、職種、雇用部課、予算区分は修正されません。行={0}','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1010','職種がTA,SA以外の場合、科目コード、クラスコードは登録・修正されません。行={0}','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1011','職種がLA,一般の場合、教員コードは登録・修正されません。行={0}','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1012','職種がTA,SA,一般以外の場合、予算区分は登録されません。行={0}','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1013','個別単価設定は許可されていませんので、個別単価は登録・修正されません。行={0}','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0001','登録しました。','Registered.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0002','削除しました。','Deleted.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0003','データ取込が正常終了しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0004','アップロードしたファイルを確認し、問題がなければ登録を押してください。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0005','{0}処理を実行しています。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0006','キャンセルしました。','Canceled.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0007','{0}処理が正常終了しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0008','ログアウトしました。','Logged out.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0009','サーバーからの印刷処理を実行しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0010','{0}チェックラン処理が正常終了しました（「登録」ボタンを押下するまで反映されません）。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0011','データ取込チェック処理が終了しました。問題がなければ登録を押してください。','The data import check process has been completed. If there are no problems, press "Register".','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0099','公開を中止しました。','Open was called off.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1001','承認しました。','Approved','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1002','修正しました。','Corrected','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1003','差し戻しました。','Returned','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1004','督促メールを送信しました。','Reminder email sent.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K0001','削除してもよろしいですか?','Are you sure you want to delete it?','4','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K1001','{0}支給日の給与計算を行います。よろしいですか？','{0}Payroll calculation on the date of payment. Are you sure?','4','2',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K1002','{0}支給日の給与再計算を行います。よろしいですか？','{0}Recalculate payroll on the date paid. Are you sure?','4','2',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K1003','差戻を含む勤務を一括承認しようとしています。よろしいですか？','Trying to approve a batch of work including Returnings. Are you sure?','4','2',now(),'KSS','IKOU',now());

COMMIT;
