TRUNCATE TABLE MessageMaster;
BEGIN TRANSACTION;
INSERT INTO MessageMaster VALUES ( 'E0001','検索条件に該当するデータが存在しません。','Does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0002','{0}を入力してください。','{0} is required.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0003','対象が選択されていません。','The subject has not been selected.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0005','ユーザＩＤまたはパスワードが不正です。','User ID or password is invalid.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0006','システムを利用する権限がありません。 ({0})','You do not have permission to use the system. ({0})','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0007','ログインIDに事務室が割り当てられていません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0009','「{0}」は、機種依存文字のため入力できません。※“タブ”や一部の文字は「」の中が空欄で表示されます。','The [{0}] is a platform dependent character and cannot be entered. *"Tabs" and some characters are displayed with a blank space in the brackets.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0012','{0}に{1}以外が入力されています。','Something other than {1}has been entered in {0}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0016','既に存在しています。','It already exists.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0017','指定された{0}は存在しません。','Specified {0} does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0019','サーバーからの印刷処理に失敗しました。{0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0025','{0}は日付または時刻として正しくありません。','{0} is incorrect as a date or time.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0028','{0}は{1}より未来の日付を指定することはできません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0029','{0}は{1}より過去の日付を指定することはできません。','{0} does not allow you to specify a date before {1}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0034','{0}は小さい方から順に入力してください。','For {0}, please enter in order from smallest.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0035','{0}は{1}から{2}の範囲で入力してください。','For {0} please enter a range of {1} to {2}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0040','{0}に同じ内容は入力できません。','Same content cannot be entered into {0}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0041','{0}と{1}に同じ内容は入力できません。','Same content cannot be entered into {0} and {1}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0042','対象のデータが存在しません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0044','エラーの内容を確認してください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0045','本処理は、他のユーザで実行中です。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0047','{0}が選択されていない場合は、{1}は入力できません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0052','対象ファイルが存在しません。','The target file does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0057','{0}は、{1}桁で入力してください。','{0}, please enter {1} digits.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0058','{0}は、{1}桁以内で入力してください。','{0}, please enter {1} digits or less.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0059','{0}は、{1}桁以上で入力してください。','{0}, please enter {1} digits or more.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0060','該当データは、他のユーザで削除されました。','Deleted by another user.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0061','他のユーザで内容が更新されました。現在の内容を破棄の上、再オペレーションしてください。','Content has been updated by another user. Please discard the current content and try again.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0062','処理に時間がかかり過ぎるため、処理を中断しました。条件を変更して再度実行してください。','Process has timed out. Please change the conditions and try again.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0069','利用可能期間を超過しました。','Available runtime has been exceeded.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0075','Excelファイルの「{0}」シートにデータがありません。','Excel file "{0}" There is no data in the sheet.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0076','Excelファイルに「{0}」シートが存在しません。','The Excel file "{0}" sheet does not exist.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0077','Excelファイルの「{0}」シートにヘッダ行がありません。','Excel file "{0}" does not have a header line on the sheet.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0078','Excelファイルのヘッダ行が違います。行={0} 列={1} 正しい値={2} 実際の値={3}','Header line in the Excel file is different. Line={0} column={1} correct value={2} actual value={3}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0079','Excelファイルにデータがありません。','There is no data in the Excel file.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0080','{0}を入力してください。行={1}','{0} is required. Line={1}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0081','{0}は、{1}桁で入力してください。行={2}','{0}, please enter in the {1} digits. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0082','{0}は、{1}桁以内で入力してください。行={2}','{0}, please enter within {1} digits. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0083','{0}は、{1}桁以上で入力してください。行={2}','{0}, please enter as {1} or more digits. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0084','{0}に{1}以外が入力されています。行={2}','{0} than {1} it has been entered into. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0085','{0}が{1}に登録されていません。行={2}','{0} is not registered to {1}. Line={2}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0086','ファイルの上限サイズを超えています。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0087','ファイルが不正です。{0}','File is invalid. {0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0088','画像ファイルではありません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0090','{0}処理を実行できませんでした。システム管理者に問い合わせてください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0091','{0}処理でエラーが発生しました。エラー内容を確認してください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0092','キー項目が同じデータが存在します。行={0} キー項目={1}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0093','{0}は小さい方から順に入力してください。行={1}','Please enter in order from {0} small to large. Line={1}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0094','{0}は{1}から{2}の範囲で入力してください。行={3}','{0} Please enter in the range of {2} from {1}. Line={3}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0095','指定された{1}は存在しません。行={0}','Specified {1} does not exist. Line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0096','指定された{1}は既に存在しています。行={0}','Specified {1} already exists. Line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0098','取込ファイルの項目数が{1}ではありません。行={0}','The number of items in the uploaded file is not {1}. Line={0}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0099','{1}行目と同じです。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0100','存在しない{1}です。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0101','{0}のアップロードでエラーが発生しました。','An error has occurred in the upload of {0}.','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E0102','{0}は日付または時刻として正しくありません。行={1}','{0} is incorrect as a date or time. Line={1}','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1001','指定された{0}は既に存在しています。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1002','検索条件が不足しています。検索条件の指定を追加してください。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1003','一切の項目の変更は不可です。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1004','修正不可項目への修正があります。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1005','差戻理由と差戻者以外は変更できません。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1006','指定された{1}は科目の担当教員ではありません。行={0}','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1007','入力された勤務時間は既に登録されています。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1008','雇用期間外のため、登録できません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1009','深夜時間の登録はできません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1010','勤務時間が6時間を超える場合、1時間以上の控除時間が必要です。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1011','勤務時間が週28時間を超えるため、登録できません。','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1012','','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'E1013','','','1','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0001','本機能は未実装です。','Under construction.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0005','{0}件を超えたため、これ以上表示できません。条件で絞り込んでください。','Search terms exceed the maximum of {0} results. Please refine conditions.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0006','{0}件を超えたため、これ以上表示できません。処理を実行し、件数を減らしてください。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0007','{0}件を超えたため、{0}件までの検索結果を表示します。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0008','{0}件を超えたため、表示できません。科目名を追記するか他の条件も指定してください。','Search terms exceed the maximum of {0} results. Please add course name or refine other conditions.','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W0009','今回の成績記入にて、再履修回数を超えました。問題がある場合は訂正して下さい。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1001','差戻を含む勤務を一括承認しようとしています。問題がなければ登録を押してください。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1002','同一日勤務情報が既に登録されています。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1003','勤務時間が週20時間を超えています。週28時間は超えないようにしてください。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1004','1日の勤務時間が{0}時間を超えないようにしてください。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1005','1週間の勤務時間が{0}時間を超えています。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'W1006','1ヶ月の勤務時間が{0}時間を超えています。','','2','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0001','登録しました。','Registered.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0002','削除しました。','Deleted.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0003','データ取込が正常終了しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0004','アップロードしたファイルを確認し、問題がなければ登録を押してください。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0005','{0}処理を実行しています。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0006','キャンセルしました。','Canceled.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0007','{0}処理が正常終了しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0008','ログアウトしました。','Logged out.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0009','サーバーからの印刷処理を実行しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0010','{0}チェックラン処理が正常終了しました（「登録」ボタンを押下するまで反映されません）。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0020','学生からの未読の回答が{0}件あります','{0} unread replies from students.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0021','担当者からのお知らせが未読{0}件、未回答{1}件あります','{0} unread message(s) from instructor, {1} unanswered message(s).','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0022','担当者からのお知らせが未読{0}件あります','{0} unread message(s) from instructor.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0023','担当者からのお知らせが未回答{0}件あります','{0} unanswered message(s) from instructor.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0024','事務室からのお知らせが未読{0}件、未回答{1}件あります','{0} unread message(s) from office, {1} unanswered message(s).','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0025','事務室からのお知らせが未読{0}件あります','{0} unread message(s) from office.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0026','事務室からのお知らせが未回答{0}件あります','{0} unanswered message(s) from office.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0027','全ての回答・添付ファイルダウンロード(約{0}MB)','Download all replies and attachments (approx, {0}MB)','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0028','添付ファイルダウンロード(約{0}MB)','Downlad attachment (approx. {0}MB)','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0030','担当者の操作によりメッセージが取り消されました。','Message has been canceled by the instructor.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0031','事務室の操作によりメッセージが取り消されました。','Message has been canceled by the office.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0034','{0} 変更','Updated on {0}','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0035','{0}に変更','Change to {0}','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0036','{0}より変更','Change from {0}','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0037','{0}から{1}に変更','Change from {0} to {1}','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0040','メッセージを受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your message has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0041','住所変更を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your address has been changed. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0042','先行登録申請を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your application for advanced registration has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0043','先行登録（ゼミ）申請を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your application for advanced registration of the seminar(s) has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0044','履修登録（修正）を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your application for course registration has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0045','履修中止を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your application for course withdrawal has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0046','先行登録削除を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your request to delete your advanced registration has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0047','副専攻登録・取消を受け付けました。内容はメールで自動送信されますので、必ず確認してください。<br>副専攻履修状況画面については、翌AM1:00～AM5:00の間に反映されます。','Your registration (cancellation) of minor subjects has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.<br>Your registration status of minor subjects will be updated between 1 a.m. and 5 a.m. on the following day.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0048','免許資格課程仮登録を受付しました。登録内容はメールで確認してください。<br>なお、履修状況画面については、本登録完了後に確認できるようになります。','不要','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0049','免許資格課程本登録を受付しました。登録内容はメールで確認してください。<br>なお、履修状況画面については、本登録完了後に確認できるようになります。<br>受付期間後に登録内容を修正、削除する場合は、所属学部の主たる校地の免許資格課程センター事務室にて<br>手続きを行ってください。','不要','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0050','教職免許申請希望を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','不要','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0051','授業評価アンケートの回答を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your course evaluation survey has been accepted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0052','メッセージ登録を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your message has been registered. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0053','授業講評を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your course review has been submitted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0054','担当教員設定を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Representative instructor for the course has been set. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0055','試験実施要領登録・取消を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your exam information has been submitted (deleted). You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0056','追試験の試験実施要領登録・取消を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your makeup exam information has been submitted (deleted). You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0057','レポート実施要領登録・取消を受け付けました。内容はメールで自動送信されますので、必ず確認してください。<br>また、登録・取消を受け付けた内容は「レポート実施状況確認・編集」から確認することができます。','Your report information has been submitted (deleted). You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.<br>You can also confirm the current status including the change records in the "Confirm/edit implementation status".','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0058','出講調査の回答を受け付けました。','Your tentative schedule has been submitted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0059','授業評価アンケートの質問設定・コメント登録を受け付けました。内容はメールで自動送信されますので、必ず確認してください。','Your questionnaire of course evaluation survey and your feedback has been submitted. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0060','採点（仮更新）を受け付けました。','Your preliminary grades to be tallied have been submitted.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0061','採点（本更新）を受け付けました。登録完了メールが自動送信されます。','Your tentative grades have been submitted.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0062','メール送信設定を受け付けました。','Your e-mail setting has been accepted.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0063','メッセージ取消を受け付けました。','Your message has been deleted.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0064','授業評価アンケートの質問設定・コメント削除を受け付けました。','Your questionnaire of course evaluation survey has been submitted and your feedcback has been deleted.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0065','作業用成績を受け付けました。','Your grades have been finalized. You will receive a confirmation e-mail shortly. Please be sure to check your e-mail.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0066','メールアドレス設定を受け付けました。','Your e-mail address has been configured.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0067','休講情報の登録・削除を受け付けました。内容はメールで自動送信されますので、必ず確認してください。<br>また、登録・削除を受け付けた内容は「休講状況確認・修正」から確認することができます。','Class cancellation has been submitted (deleted). You will receive a confirmation e-mail shortly. Please be sure to check your e-mail. The cancellation (deletion) can be confirmed in the "Status of class cancellation/revision" section.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I0099','公開を中止しました。','Open was called off.','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1001','承認しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1002','修正しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1003','差し戻しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'I1004','督促メールを送信しました。','','3','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K0001','削除してもよろしいですか?','Are you sure you want to delete it?','4','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K0002','メッセージを削除します。よろしいですか。','Delete message. Are you sure?','4','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K0003','公開を取り止めます。よろしいですか。','Cease publication. Are you sure?','4','1',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K1001','{0}支給日の給与計算を行います。よろしいですか？','','4','2',now(),'KSS','IKOU',now());
INSERT INTO MessageMaster VALUES ( 'K1002','{0}支給日の給与再計算を行います。よろしいですか？','','4','2',now(),'KSS','IKOU',now());

COMMIT;
