ProxyPass /gakuseikinmu/activex !
alias /gakuseikinmu/activex C:\gakuseikinmu\activex
<Location /gakuseikinmu/activex>
  Require all granted
</Location>

ProxyPass /gakuseikinmu/css !
alias /gakuseikinmu/css C:\gakuseikinmu\css
<Location /gakuseikinmu/css>
  Require all granted
</Location>

ProxyPass /gakuseikinmu/images !
alias /gakuseikinmu/images C:\gakuseikinmu\images
<Location /gakuseikinmu/images>
  Require all granted
</Location>

ProxyPass /gakuseikinmu/js !
alias /gakuseikinmu/js C:\gakuseikinmu\js
<Location /gakuseikinmu/js>
  Require all granted
</Location>

ProxyPass /gakuseikinmu ajp://localhost:50000/gakuseikinmu

<Location "/gakuseikinmu">
  ErrorDocument 404 /maintenance.html
  ErrorDocument 503 /maintenance.html
</Location>
