ProxyPass /gakuseikinmu01/activex !
alias /gakuseikinmu01/activex C:\gakuseikinmu01\activex
<Location /gakuseikinmu01/activex>
  Require all granted
</Location>

ProxyPass /gakuseikinmu01/css !
alias /gakuseikinmu01/css C:\gakuseikinmu01\css
<Location /gakuseikinmu01/css>
  Require all granted
</Location>

ProxyPass /gakuseikinmu01/images !
alias /gakuseikinmu01/images C:\gakuseikinmu01\images
<Location /gakuseikinmu01/images>
  Require all granted
</Location>

ProxyPass /gakuseikinmu01/js !
alias /gakuseikinmu01/js C:\gakuseikinmu01\js
<Location /gakuseikinmu01/js>
  Require all granted
</Location>

ProxyPass /gakuseikinmu01 ajp://localhost:50001/gakuseikinmu01

<Location "/gakuseikinmu01">
  ErrorDocument 404 /maintenance.html
  ErrorDocument 503 /maintenance.html
</Location>
